ABSOLUATE_PATH="D:\\new-automation\\wechat-automation\\"
BACK_IMAGE="pics\\Back.png"
CHATS_IMAGE="pics\\Chats-white-english.png"
DISCOVER_IMAGE="pics\\Discover-white-english.png"
MOMENTS_IMAGE="pics\\Moments_icon.png"
CAMERA_IMAGE="pics\\Camera.png"
MAIN_PAGE_GREEN_IMAGE="pics\\Chats-green.png"
MAIN_PAGE_WHITE_IMAGE="pics\\Chats-white.png"
THREE_DOTS="pics\\Three-dots.png"

